### ISSUE TITLE
Geocode Every Household

### ISSUE THREAD

**Issue by BenGalewsky** [CUHackNight/voter-data#1]

**Comment by bevwilso** [comment]
The election day voters file contained 48,524 total records and using this alternate approach only 374 (0.77%) did not fully match on the first try. Similarly, the absentee voters file contained 45,400 total records and only 349 (0.77%) did not fully match on the first try using the dual addresses locator. 

The attached zip file contains a shapefile with point locations for all of the correctly geocoded addresses in the original election day file and the absentee file. 

There are also .dbf file that contain the unmatched records from the original election day file and the absentee file.

There were 723 unmatched records (total) from both the absentee and election day voter datasets.
